# From https://github.com/IBM/blockchain-network-on-kubernetes/pull/28
# Note: not currently used, a docker sidecar for each peer is used instead

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-pv
  labels:
    type: local
    name: dockervolume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp-docker-pv"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
      matchLabels:
        name: dockervolume