apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hlf-orderer--frontends--1000
spec:
  serviceName: hlf-orderer--frontends--1000
  selector:
    matchLabels:
      app: hlf-orderer--frontends--1000
  template:
    metadata:
      labels:
        name: hlf-orderer
        org: hlf-orderer--frontends
        app: hlf-orderer--frontends--1000
        spec:
          volumes:
          - name: orderingnode-material
            secret:
              # TODO correct keys etc.
              secretName: frontend-material
              items:
              - key: genesis.block
                path: genesis.block
              - key: hosts.config
                path: hosts.config
              - key: node.config
                path: node.config
              - key: system.config
                path: system.config
              - key: keystore.pem
                path: keys/keystore.pem
              - key: cert1000.pem
                path: keys/cert1000.pem
              {{- range $ii, $e := until ($org.Template.Count | int) }}
              - key: cert{{ $ii | toString }}.pem
                path: keys/cert{{ $ii | toString }}.pem
              {{- end }}
    
          {{- if $.Values.hostAliases }}
          hostAliases:
          {{- range $i, $alias := $.Values.hostAliases }}
          - ip: {{ $alias.ip }}
            hostnames: {{ $alias.hostnames }}
          {{- end }}
          {{- end }}{{""}}
    
          containers: 
          - name: orderer
            image: bftsmart/fabric-orderingnode:amd64-1.3.0
            args: ["{{ $i | toString }}"]
    
            volumeMounts:
            - mountPath: /bft-config/config/
              name: orderingnode-material
    
            env:
            - name: NODE_CONFIG_DIR
              value: /bft-config/config/