apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hlf-orderer--orderingnodes--0
spec:
  serviceName: hlf-orderer--orderingnodes--0
  selector:
    matchLabels:
      app: hlf-orderer--orderingnodes--0
  template:
    metadata:
      labels:
        name: hlf-orderer
        org: hlf-orderer--orderingnodes
        app: hlf-orderer--orderingnodes--0
    spec:
      volumes:
      - name: orderingnode-material
        secret:
          secretName: orderingnode-material--0
          items:
          - key: genesis.block
            path: genesis.block
          - key: hosts.config
            path: hosts.config
          - key: node.config
            path: node.config
          - key: system.config
            path: system.config
          - key: keystore.pem
            path: keys/keystore.pem
          - key: cert1000.pem
            path: keys/cert1000.pem
          - key: cert0.pem
            path: keys/cert0.pem
          - key: cert1.pem
            path: keys/cert1.pem
          - key: cert2.pem
            path: keys/cert2.pem
          - key: cert3.pem
            path: keys/cert3.pem

      #
      # hostAliases:
      #
      # - ip: 10.106.44.210
      #   hostnames: [1000.yoleanfront.se]
      #
      # - ip: 10.105.242.83
      #   hostnames: [0.yoleanord.se]
      #
      # - ip: 10.97.1.163
      #   hostnames: [1.yoleanord.se]
      #
      # - ip: 10.101.187.86
      #   hostnames: [2.yoleanord.se]
      #
      # - ip: 10.104.245.52
      #   hostnames: [3.yoleanord.se]
      #
      #

      containers: 
      - name: orderer
        image: bftsmart/fabric-orderingnode:amd64-1.3.0
        args: ["0"]

        volumeMounts:
        - mountPath: /bft-config/config/
          name: orderingnode-material

        env:
        - name: NODE_CONFIG_DIR
          value: /bft-config/config/
---