{{- $vars:= dict "firstKey" true }}
{{- $forg := index $.Values.OrdererOrgs 0 }}
{{- $commonName := printf "1000.%s" $forg.Domain }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: frontend-msp
  labels:
    orgName: {{ $forg.Name }}
data:
  orderer.yaml: |-
      {{ $.Files.Get "orderingnode-material/frontend/orderer.yaml" | b64enc }}
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/signcerts/%s-cert.pem" $forg.Domain $commonName $commonName ) | b64enc }}
  cacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/cacerts/ca.%s-cert.pem" $forg.Domain $commonName $forg.Domain) | b64enc }}
  admincert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/admincerts/Admin@%s-cert.pem" $forg.Domain $commonName $forg.Domain ) | b64enc }}
  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/keystore/*" $forg.Domain $commonName ) }}
  {{- if not $vars.firstKey }}
    {{ fail (printf "Multiple private keys in folder: crypto-config/ordererOrganizations/%s/orderers/%s/msp/keystore/" $forg.Domain $commonName ) }}
  {{- end }}
  key.pem: |-
      {{ $.Files.Get $path | b64enc }}
      {{- $_ := set $vars "firstKey" false }}
  {{- end }}
---