{{- $org := index $.Values.OrdererOrgs 0 }}
{{- range $i, $host := $org.Specs }}
{{- $commonName := printf "%s.%s" ($host.Hostname | toString) $org.Domain }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | toString }}-tls
  labels:
    orgName: {{ $org.Name }}
    commonName: {{ $commonName }}
data:
  {{ ($.Files.Glob (printf "crypto-config/ordererOrganizations/%s/orderers/%s/tls/*" $org.Domain $commonName)).AsSecrets | nindent 2 }}
---
{{- end }} {{- /* org.Specs */ -}}
